Repository nestjs/nest, pull requests merged in 2019-05, with the labels that each got.

#2243 fix(sample): Update sample to avoid deprecated secretOrPrivateKey
  sample/19-auth/src/auth/auth.module.ts
Labels: status: wip ⚡️, type: example

#2245 chore(): Add issue templates
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Feature_request.md
  .github/ISSUE_TEMPLATE/Regression.md
  .github/ISSUE_TEMPLATE/Support_question.md
Labels: type: enhancement :wolf:

#1601 feat(@nestjs/core): Add init function on NestApplicationContext to API
  packages/common/interfaces/nest-application-context.interface.ts
  packages/core/nest-application-context.ts
  packages/core/nest-application.ts
  packages/microservices/nest-microservice.ts
Labels: type: feature :tada:

#2272 bugfix(core): Upgrade opencollective dependency
  package-lock.json
  package.json
  packages/core/package.json
Labels: type: deps

#2240 feature(microservices): Return correct client type in ClientProxyFactory
  packages/microservices/client/client-proxy-factory.ts
Labels: scope: microservices, type: enhancement :wolf:

#2254 class-transformer enableImplicitConversion flag added
  packages/common/interfaces/external/class-transform-options.interface.ts
Labels: scope: common, type: enhancement :wolf:

#1562 bugfix(common) allow classes as data parameter in createParamDecorato…
  packages/common/decorators/http/create-route-param-metadata.decorator.ts
  packages/common/test/decorators/create-param-decorator.spec.ts
Labels: scope: core
