Repository nestjs/nest, pull requests merged in 2019-07, with the labels that each got.

#2516 Run integration tests with TravisCI
  .travis.yml
  integration/graphql/tsconfig.json
  package.json
Labels: type: build

#2510 chore(): Remove Gitter badge
  Readme.md
  readme_zh.md
Labels: status: done 👏, type: docs :page_facing_up:

#2496 feat(Multer): Add any file interceptor
  packages/platform-express/multer/interceptors/any-files.interceptor.ts
  packages/platform-express/test/multer/interceptors/any-files.interceptor.spec.ts
Labels: scope: common, type: enhancement :wolf:

#2512 Bugfix: Make errors serializable by default
  packages/common/exceptions/http.exception.ts
  packages/common/test/exceptions/http.exception.spec.ts
  packages/microservices/exceptions/rpc-exception.ts
  packages/microservices/test/exceptions/rpc-exception.spec.ts
  packages/websockets/errors/ws-exception.ts
  packages/websockets/test/exceptions/ws-exception.spec.ts
Labels: scope: core, type: enhancement :wolf:

#2527 ci(): Build samples in Pipeline
  .travis.yml
  gulpfile.js
  package.json
  sample/01-cats-app/src/common/middleware/logger.middleware.ts
  sample/01-cats-app/tsconfig.build.json
  sample/02-gateways/package.json
  sample/08-webpack/package.json
  sample/08-webpack/webpack.config.js
  sample/12-graphql-apollo/tsconfig.json
  sample/14-mongoose-base/tsconfig.build.json
  sample/19-auth/tsconfig.build.json
  sample/20-cache/src/common/http-cache.interceptor.ts
  sample/20-cache/tsconfig.build.json
  sample/21-serializer/tsconfig.build.json
  sample/22-graphql-prisma/tsconfig.json
  sample/23-type-graphql/tsconfig.json
Labels: type: build, type: enhancement :wolf:

#2417 sample(new auth sample): matches new auth chapter
  sample/24-auth-jwt/.gitignore
  sample/24-auth-jwt/nest-cli.json
  sample/24-auth-jwt/nodemon-debug.json
  sample/24-auth-jwt/nodemon.json
  sample/24-auth-jwt/package.json
  sample/24-auth-jwt/src/app.controller.spec.ts
  sample/24-auth-jwt/src/app.controller.ts
  sample/24-auth-jwt/src/app.module.ts
  sample/24-auth-jwt/src/app.service.ts
  sample/24-auth-jwt/src/auth/auth.module.ts
  sample/24-auth-jwt/src/auth/auth.service.spec.ts
  sample/24-auth-jwt/src/auth/auth.service.ts
  sample/24-auth-jwt/src/auth/constants.ts
  sample/24-auth-jwt/src/auth/jwt.strategy.ts
  sample/24-auth-jwt/src/auth/local.strategy.ts
  sample/24-auth-jwt/src/main.ts
  sample/24-auth-jwt/src/users/users.module.ts
  sample/24-auth-jwt/src/users/users.service.spec.ts
  sample/24-auth-jwt/src/users/users.service.ts
  sample/24-auth-jwt/tsconfig.build.json
  sample/24-auth-jwt/tsconfig.json
  sample/24-auth-jwt/tslint.json
  scripts/test.sh
Labels: type: example

#2548 bugfix(Multer) export AnyFilesInterceptor
  packages/platform-express/multer/interceptors/index.ts
Labels: scope: platform, status: done 👏

#2611 docs(sample): add sample for @nestjs/serve-static
  sample/24-serve-static/.gitignore
  sample/24-serve-static/client/index.html
  sample/24-serve-static/package-lock.json
  sample/24-serve-static/package.json
  sample/24-serve-static/src/app.module.ts
  sample/24-serve-static/src/main.ts
  sample/24-serve-static/tsconfig.build.json
  sample/24-serve-static/tsconfig.json
  sample/24-serve-static/tslint.json
Labels: status: blocked 🚫, type: example
